#! /bin/sh
# /etc/init.d/gunicorn

### BEGIN INIT INFO
# Provides:          gunicorn
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: gunicorn
# Description:       gunicorn daemon
### END INIT INFO

# Written by: Matthew Hartstonge
# Date Written: 20/09/2014

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Gunicorn "
    /YOUR/DJANGO/bin/gunicorn -c /YOUR/DJANGO/gunicorn_config.py PROJECT_NAME.wsgi --daemon --pid /YOUR/DJANGO/bin/gunicorn.pid
    ;;
  stop)
    echo "Stopping Gunicorn"
    cat /YOUR/DJANGO/bin/gunicorn.pid | xargs kill
    ;;
  restart)
    echo "Restarting Gunicorn"
	cat /YOUR/DJANGO/bin/gunicorn.pid | xargs kill -HUP
	;;
  *)
    echo "Usage: /etc/init.d/gunicorn {start|stop|restart}"
    exit 1
    ;;
esac

exit 0